blank_issues_enabled: false
contact_links:
  - name: Velero Q&A
    url: https://github.com/velero-io/velero/discussions/categories/community-support-q-a
    about: Have questions about Velero? Please ask them here.
